#!/bin/bash
# 快速完成Function Call功能实现的脚本

echo "=== Function Call 功能实现脚本 ==="
echo ""
echo "当前状态："
echo "✅ vlm.py - 已完成"
echo "🔄 nav_agent.py - 需要手动完成剩余部分"
echo "⏳ nav_server.py - 待修改"
echo "⏳ llm_nav_client.py - 待修改"
echo ""
echo "由于代码修改量很大，建议按照以下步骤手动完成："
echo ""
echo "步骤1: 备份文件"
echo "  cp nav_agent.py nav_agent.py.backup"
echo "  cp nav_server.py nav_server.py.backup"
echo "  cp llm_nav_client.py llm_nav_client.py.backup"
echo ""
echo "步骤2: 编辑 nav_agent.py"
echo "  1. 删除以下方法（约400行）："
echo "     - get_history_summary() (行192-242)"
echo "     - _transform_waypoint_to_current_base() (行248-310)"
echo "     - _can_project_waypoint() (行312-350)"
echo "     - _determine_frame_type() (行352-400)"
echo ""
echo "  2. 从 nav_agent_fc_methods.py 复制所有方法到 _build_initial_prompt() 之后"
echo ""
echo "  3. 找到 _nav() 方法（约行950），替换为："
echo "     def _nav(self, obs, goal, iter, goal_description=''):"
echo "         return self._nav_with_function_call(obs, goal, iter, goal_description)"
echo ""
echo "步骤3: 编辑 nav_server.py"
echo "  在 /navigation_step 端点的 action 处理部分添加："
echo "  if isinstance(action, dict) and action.get('action_type') == 'go_to_waypoint':"
echo "      target_pos = action['target_pos']"
echo "      target_yaw = action['target_yaw']"
echo "      goal_pose = build_goal_pose(target_pos[0], target_pos[1], target_pos[2], target_yaw)"
echo "      return jsonify({'action_type': 'go_to_waypoint', ...})"
echo ""
echo "步骤4: 编辑 llm_nav_client.py"
echo "  在 run() 方法的 action 处理部分添加："
echo "  if action_type == 'go_to_waypoint':"
echo "      self.navigate_to_pose(goal_pose_stamped)"
echo ""
echo "详细说明请查看 IMPLEMENTATION_GUIDE.md"
echo ""
echo "完成后测试："
echo "  python nav_server.py --port 1874"
echo "  python llm_nav_client.py --goal chair"
